### ISSUE TITLE
it is not working well in scrollview

### ISSUE THREAD

**Issue by ebadahmed** [pookie13/ZoomImage#1]
thanks alot for writing this class,
i have an issue while using scrollview in which i have applied this class, when we put this thing in scroll view and when we zoom in image it expand but we cannot see the whole image 
i will be very thankful to you if you look into this matter 
P.S: sorry for my bad english

**Comment by pookie13** [comment]
thanks for notifying me about this issue.as I understood your problem, you need to handle scroll for same. please try this, it should work for you
`touchImageView.setOnTouchListener(new OnTouchListener() {
    // Setting on Touch Listener for handling the touch inside ScrollView
    @Override
    public boolean onTouch(View v, MotionEvent event) {
    // Disallow the touch request for parent scroll on touch of child view
    v.getParent().requestDisallowInterceptTouchEvent(true);
    return false;
    }
});
`

hopefully, it will solve your issue. and thanks again for using this lib.
